//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_management_api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("student_management_api.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add student failed.
        /// </summary>
        public static string add_student_failed {
            get {
                return ResourceManager.GetString("add_student_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rules turned off.
        /// </summary>
        public static string all_rules_turned_off {
            get {
                return ResourceManager.GetString("all_rules_turned_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rules turned on.
        /// </summary>
        public static string all_rules_turned_on {
            get {
                return ResourceManager.GetString("all_rules_turned_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later.
        /// </summary>
        public static string an_unexpected_error_occurred_Please_try_again_later {
            get {
                return ResourceManager.GetString("an_unexpected_error_occurred_Please_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change credits for a course that has students enrolled.
        /// </summary>
        public static string cannot_change_credits_for_a_course_that_has_students_enrolled {
            get {
                return ResourceManager.GetString("cannot_change_credits_for_a_course_that_has_students_enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register after the semester has ended.
        /// </summary>
        public static string cannot_register_after_the_semester_has_ended {
            get {
                return ResourceManager.GetString("cannot_register_after_the_semester_has_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unregister after the semester has started.
        /// </summary>
        public static string cannot_unregister_after_the_semester_has_started {
            get {
                return ResourceManager.GetString("cannot_unregister_after_the_semester_has_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been a class with the same ID for this course in this semester !.
        /// </summary>
        public static string class_id_already_exists {
            get {
                return ResourceManager.GetString("class_id_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class is full.
        /// </summary>
        public static string class_is_full {
            get {
                return ResourceManager.GetString("class_is_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not found.
        /// </summary>
        public static string class_not_found {
            get {
                return ResourceManager.GetString("class_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class with the same schedule and room already exists in this semester. Please choose a different schedule or room..
        /// </summary>
        public static string class_with_duplicate_schedule_and_room {
            get {
                return ResourceManager.GetString("class_with_duplicate_schedule_and_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes exist for this course. The course has been marked as inactive.
        /// </summary>
        public static string classes_exist_for_this_course_The_course_has_been_marked_as_inactive {
            get {
                return ResourceManager.GetString("classes_exist_for_this_course_The_course_has_been_marked_as_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course added successfully.
        /// </summary>
        public static string course_added_successfully {
            get {
                return ResourceManager.GetString("course_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course deleted successfully.
        /// </summary>
        public static string course_deleted_successfully {
            get {
                return ResourceManager.GetString("course_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course has been deleted, you cannot delete it again.
        /// </summary>
        public static string course_has_been_deleted {
            get {
                return ResourceManager.GetString("course_has_been_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course not found.
        /// </summary>
        public static string course_not_found {
            get {
                return ResourceManager.GetString("course_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course not found or no changes made.
        /// </summary>
        public static string course_not_found_or_no_changes_made {
            get {
                return ResourceManager.GetString("course_not_found_or_no_changes_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email domains config updated successfully.
        /// </summary>
        public static string email_domains_config_updated_successfully {
            get {
                return ResourceManager.GetString("email_domains_config_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded 30 minutes, cannot delete.
        /// </summary>
        public static string exceeded_30_minutes_cannot_delete {
            get {
                return ResourceManager.GetString("exceeded_30_minutes_cannot_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty not found.
        /// </summary>
        public static string faculty_not_found {
            get {
                return ResourceManager.GetString("faculty_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add class.
        /// </summary>
        public static string failed_to_add_class {
            get {
                return ResourceManager.GetString("failed_to_add_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add faculty.
        /// </summary>
        public static string failed_to_add_faculty {
            get {
                return ResourceManager.GetString("failed_to_add_faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add program.
        /// </summary>
        public static string failed_to_add_program {
            get {
                return ResourceManager.GetString("failed_to_add_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add student.
        /// </summary>
        public static string failed_to_add_student {
            get {
                return ResourceManager.GetString("failed_to_add_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add student status.
        /// </summary>
        public static string failed_to_add_student_status {
            get {
                return ResourceManager.GetString("failed_to_add_student_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create course.
        /// </summary>
        public static string failed_to_create_course {
            get {
                return ResourceManager.GetString("failed_to_create_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log enrollment history.
        /// </summary>
        public static string failed_to_log_enrollment_history {
            get {
                return ResourceManager.GetString("failed_to_log_enrollment_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register for the course.
        /// </summary>
        public static string failed_to_register_for_the_course {
            get {
                return ResourceManager.GetString("failed_to_register_for_the_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update student grade.
        /// </summary>
        public static string failed_to_update_student_grade {
            get {
                return ResourceManager.GetString("failed_to_update_student_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action specified. Use &apos;register&apos; or &apos;unregister&apos;.
        /// </summary>
        public static string invalid_action_specified_Use_register_or_unregister {
            get {
                return ResourceManager.GetString("invalid_action_specified_Use_register_or_unregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid composited ID for class.
        /// </summary>
        public static string invalid_composited_id_for_class {
            get {
                return ResourceManager.GetString("invalid_composited_id_for_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid config type.
        /// </summary>
        public static string invalid_config_type {
            get {
                return ResourceManager.GetString("invalid_config_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email domain.
        /// </summary>
        public static string invalid_email_domain {
            get {
                return ResourceManager.GetString("invalid_email_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format. Supported formats are &apos;json&apos; and &apos;excel&apos;.
        /// </summary>
        public static string invalid_format_Supported_formats_are_json_and_excel {
            get {
                return ResourceManager.GetString("invalid_format_Supported_formats_are_json_and_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input data.
        /// </summary>
        public static string invalid_input {
            get {
                return ResourceManager.GetString("invalid_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or empty file.
        /// </summary>
        public static string invalid_or_empty_file {
            get {
                return ResourceManager.GetString("invalid_or_empty_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string invalid_password {
            get {
                return ResourceManager.GetString("invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string invalid_phone_number {
            get {
                return ResourceManager.GetString("invalid_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string invalid_request {
            get {
                return ResourceManager.GetString("invalid_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request type.
        /// </summary>
        public static string invalid_request_type {
            get {
                return ResourceManager.GetString("invalid_request_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid student information found.
        /// </summary>
        public static string invalid_student_information_found {
            get {
                return ResourceManager.GetString("invalid_student_information_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid student status transition.
        /// </summary>
        public static string invalid_student_status_transition {
            get {
                return ResourceManager.GetString("invalid_student_status_transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes applied.
        /// </summary>
        public static string no_changes_applied {
            get {
                return ResourceManager.GetString("no_changes_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enrollment found to unregister or the student has completed the course.
        /// </summary>
        public static string no_enrollment_found_to_unregister_or_the_student_has_completed_the_course {
            get {
                return ResourceManager.GetString("no_enrollment_found_to_unregister_or_the_student_has_completed_the_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file uploaded.
        /// </summary>
        public static string no_file_uploaded {
            get {
                return ResourceManager.GetString("no_file_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules found or no changes applied.
        /// </summary>
        public static string no_rules_found_or_no_changes_applied {
            get {
                return ResourceManager.GetString("no_rules_found_or_no_changes_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more statuses are not found.
        /// </summary>
        public static string one_or_more_statuses_are_not_found {
            get {
                return ResourceManager.GetString("one_or_more_statuses_are_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number country config updated successfully.
        /// </summary>
        public static string phone_number_country_config_updated_successfully {
            get {
                return ResourceManager.GetString("phone_number_country_config_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite course not exists.
        /// </summary>
        public static string prerequisite_course_not_exists {
            get {
                return ResourceManager.GetString("prerequisite_course_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program not found.
        /// </summary>
        public static string program_not_found {
            get {
                return ResourceManager.GetString("program_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student deleted successfully.
        /// </summary>
        public static string student_deleted_successfully {
            get {
                return ResourceManager.GetString("student_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student has not passed all prerequisites.
        /// </summary>
        public static string student_has_not_passed_all_prerequisites {
            get {
                return ResourceManager.GetString("student_has_not_passed_all_prerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student not found.
        /// </summary>
        public static string student_not_found {
            get {
                return ResourceManager.GetString("student_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student not found or already deleted.
        /// </summary>
        public static string student_not_found_or_already_deleted {
            get {
                return ResourceManager.GetString("student_not_found_or_already_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student not found or no changes made.
        /// </summary>
        public static string student_not_found_or_no_changes_made {
            get {
                return ResourceManager.GetString("student_not_found_or_no_changes_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student status not found.
        /// </summary>
        public static string student_status_not_found {
            get {
                return ResourceManager.GetString("student_status_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student status rules config updated successfully.
        /// </summary>
        public static string student_status_rules_config_updated_successfully {
            get {
                return ResourceManager.GetString("student_status_rules_config_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student updated successfully.
        /// </summary>
        public static string student_updated_successfully {
            get {
                return ResourceManager.GetString("student_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students added successfully.
        /// </summary>
        public static string students_added_successfully {
            get {
                return ResourceManager.GetString("students_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered class.
        /// </summary>
        public static string successfully_registered_class {
            get {
                return ResourceManager.GetString("successfully_registered_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unregistered class.
        /// </summary>
        public static string successfully_unregistered_class {
            get {
                return ResourceManager.GetString("successfully_unregistered_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated student grade.
        /// </summary>
        public static string successfully_updated_student_grade {
            get {
                return ResourceManager.GetString("successfully_updated_student_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKPM University.
        /// </summary>
        public static string tkpm_university {
            get {
                return ResourceManager.GetString("tkpm_university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript not found.
        /// </summary>
        public static string transcript_not_found {
            get {
                return ResourceManager.GetString("transcript_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update course successfully.
        /// </summary>
        public static string update_course_successfully {
            get {
                return ResourceManager.GetString("update_course_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update faculty successfully.
        /// </summary>
        public static string update_faculty_successfully {
            get {
                return ResourceManager.GetString("update_faculty_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update program successfully.
        /// </summary>
        public static string update_program_successfully {
            get {
                return ResourceManager.GetString("update_program_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update student failed.
        /// </summary>
        public static string update_student_failed {
            get {
                return ResourceManager.GetString("update_student_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update student status successfully.
        /// </summary>
        public static string update_student_status_successfully {
            get {
                return ResourceManager.GetString("update_student_status_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is empty.
        /// </summary>
        public static string value_is_empty {
            get {
                return ResourceManager.GetString("value_is_empty", resourceCulture);
            }
        }
    }
}
