name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.203
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests and collect coverage
        run: dotnet test --collect:"Code Coverage"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
            -Dsonar.exclusions=**/*.html,**/*.sql
